root_path: null
log_path: null
db_path: null

main_parameters:
  output_version: '01'
  to_excel: true
  to_sqlite: true
  log_dir: log

database:
  dir: 'database'
  file: 'output_db_v{}.sqlite'
  benchmark_table: 'benchmark'
  metadata_table: 'metadata'

etl_output:
  excel:
    dir: 'output'
    file: 'output_excel_v{}.xlsx'
    benchmark_sheet: 'benchmark'
    metadata_sheet: 'metadata'

benchmark:
  name: 'Euronext100'
  tickers_info:
    dir: 'data'
    file: 'metadata.csv'
    column: 'Ticker_YFinance'
  columns:
    columns_date:
      - Date
    columns_numeric:
      - Open
      - High
      - Low
      - Close
      - Volume
    columns_string:
      - Ticker
    columns_to_drop: []
    columns_new_names:
      Date: date
      Ticker: ticker
      Open: open
      High: high
      Low: low
      Close: close
      Volume: volume

  logger:
    logname: "etl_benchmark_logger"
    filename: "etl_benchmark.log"

metadata:
  dir: 'data'
  file: 'metadata.csv'
  columns:
    columns_date: []
    columns_numeric: []
    columns_string:
      - Ticker_YFinance
      - Sector_ICB
      - Country
    columns_to_drop:
      - Company
    columns_new_names:
      Ticker_YFinance: ticker
      Sector_ICB: sector
      Country: country

  logger:
    logname: "etl_metadata_logger"
    filename: "etl_metadata.log"

streamlit:
  export:
    excel:
      dir: 'downloads'
      file: 'dl_excel_v{}.xlsx'
    sqlite:
      dir: 'downloads'
      file: 'dl_sqlite_v{}.db'
  portfolio:
    max_nb_tickers: 3
    default_tickers:
      - 'BNP.PA'
      - 'KER.PA'
      - 'INGA.AS'
  performance:
    risk_free_rate: 0.0
    trading_days_per_year: 252
    metrics:
      - cumulative_return
      - annualized_volatility
      - max_drawdown
      - sharpe_ratio
  logger:
    logname: "view_streamlit_logger"
    filename: "view_streamlit.log"