root_path: null

main_parameters:
  output_version: '01'
  to_excel: true
  to_sqlite: true

database:
  dir: 'database'
  file: 'output_db_v{}.sqlite'
  portfolio_table: 'portfolio_data'
  benchmark_table: 'benchmark_data'
  metadata_table: 'metadata'

etl_output:
  excel:
    dir: 'output'
    file: 'output_excel_v{}.xlsx'
    portfolio_sheet: 'portfolio'
    benchmark_sheet: 'benchmark'
    metadata_sheet: 'metadata'

portfolio:
  tickers:
    - 'BNP.PA'
    - 'KER.PA'
    - 'INGA.AS'
  start_date: '2020-01-01'
  end_date: '2024-01-01'

benchmark:
  ticker: '^N100'

metadata:
  dir: 'data'
  file: 'metadata.csv'
  columns:
    columns_date: []
    columns_numeric: []
    columns_string:
      - Ticker_YFinance
      - Sector_ICB
      - Country
    columns_to_drop:
      - Company
    columns_new_names:
      Ticker_YFinance: ticker
      Sector_ICB: sector
      Country: country

streamlit:
  export:
    excel:
      dir: 'downloads'
      file: 'dl_excel_v{}.xlsx'
    sqlite:
      dir: 'downloads'
      file: 'dl_sqlite_v{}.db'

  # portfolio:
  #   default_weights:
  #     'BNP.PA': 0.4
  #     'KER.PA': 0.3
  #     'INGA.AS': 0.3
  #   enforce_100_percent: true
  #   allowed_range: [0.0, 1.0]  # pour sliders

  # performance:
  #   risk_free_rate: 0.0
  #   trading_days_per_year: 252
  #   metrics:
  #     - cumulative_return
  #     - annualized_volatility
  #     - sharpe_ratio
  #     - max_drawdown
